# ========== General ==========
#[shell]
#program = "/opt/homebrew/bin/fish"
#args = ""

# ========== Font ==========
[font]
normal = { family = "PlemolJP Console NF", style = "Regular" }
size = 14

# ========== Selection ==========
[selection]
save_to_clipboard = true

# ========== Cursor ==========
[cursor]
vi_mode_style = "Underline"

# ========== Scrolling ==========
[scrolling]
history = 10000

# ========== Keyboard ==========
[keyboard]
# Example
bindings = [
    { key = "V", mods = "Control|Shift", action = "ToggleViMode" },
    # { key = "L", mods = "Control|Shift", chars = "l" },
]

# ========== Window ==========
[window]
opacity = 0.85

# ========== Colors ==========
[colors]
# transparent_background_colors = true
