Jetpack 'machakann/vim-sandwich'
Jetpack 'vim-denops/denops.vim'
Jetpack 'tomtom/tcomment_vim'
Jetpack 'tpope/vim-fugitive'
Jetpack 'airblade/vim-gitgutter'
Jetpack 'MetalPhaeton/easybracket-vim'
Jetpack 'yuki-yano/fuzzy-motion.vim'
